stages:
  - triggers

trigger_unit_test:
  stage: triggers
  trigger:
    include: '.gitlab-ci-unit-tests.yml'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "main"'

trigger_e2e_test:
  stage: triggers
  trigger:
    include: '.gitlab-ci-e2e-tests.yml'
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

trigger_mutation_test:
  stage: triggers
  trigger:
    include: '.gitlab-ci-mutation-tests.yml'
  rules:
    - when: manual
      allow_failure: true
