# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '24.x'

steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: $(nodeVersion)
    displayName: 'Install Node.js'

  - script: npm install -g yarn
    displayName: 'Install yarn'

  - script: yarn
    displayName: 'Install project dependencies'

  - script: yarn playwright install
    displayName: 'Install Playwright browsers'

  - script: yarn run e2e
    displayName: Run E2E tests
