version: 2.1

orbs:
  node: circleci/node@7.1.0

jobs:
  code_linting:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn
          name: Install project dependencies
      - run:
          command: yarn lint
          name: Code linting
  run_unit_tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn
          name: Install project dependencies
      - run:
          command: yarn run test
          name: Unit tests execution
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
      - store_test_results:
          path: ./reports/coverage/lcov-report
  run_e2e_tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn
          name: Install project dependencies
      - run:
          command: yarn playwright install --with-deps
          name: Install Playwright browsers
      - run:
          command: yarn run e2e
          name: E2E tests execution
      - store_test_results:
          path: ./playwright-report
  run_mutation_tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn
          name: Install project dependencies
      - run:
          command: yarn run test:mutation
          name: Mutation tests execution
      - store_test_results:
          path: ./reports/mutation
workflows:
  code_linting:
    jobs:
      - code_linting
  run_unit_tests:
    jobs:
      - run_unit_tests
  run_e2e_tests:
    jobs:
      - run_e2e_tests
  run_mutation_tests:
    jobs:
      - run_mutation_tests
