# CI de Nível 03 - Disparo após a conclusão de um pipeline

# nome do nosso 'pipeline'
name: 'Execução por Deploy'

# regras de disparo (gatilhos/trigger)
# gatilho de execução a partir de outro pipeline = workflow_run
on:
  workflow_run:
    workflows: ['E2E tests']
    types:
      - completed

# atividades/tarefas dentro do pipeline = jobs
