# CI de Nível 03 - Disparo após a conclusão de um pipeline

# nome do nosso 'pipeline'
name: 'Execução por Deploy'

# regras de disparo (gatilhos/trigger)
# gatilho de execução a partir de outro pipeline = workflow_run
on:
  workflow_run:
    workflows: ['E2E tests']
    types:
      - completed

# atividades/tarefas dentro do pipeline = jobs
jobs:
  build-and-deploy:
    # máquina que o job vai executar
    runs-on: ubuntu-latest

    # condicional - if
    # if: ${ expressão }
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # passos do script de teste
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env

      - name: Create Report files
        run: |
          mkdir -p site/e2e
          cp -r reports/e2e/* site/e2e

      - name: Publish GitHub Pages
        uses: peaceiris/actions-ghpages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
