name: 'E2E tests'

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: E2E Tests Report
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install project dependencies
        run: yarn

      - name: Install Playwright browsers
        run: yarn playwright install

      - name: Run E2E tests
        run: yarn run e2e

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./playwright-report

      - name: Upload GitHub Pages artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./playwright-report

  deploy-github-pages:
    permissions:
      pages: write
      id-token: write

    environment:
      name: E2E Tests Report
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: e2e-tests

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
