name: 'E2E tests'

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env

      - name: Install Playwright browsers
        run: yarn playwright install

      - name: Run E2E tests
        run: yarn run e2e

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./playwright-report

      - name: Create Report files
        run: |
          mkdir -p site/e2e
          cp -r ./playwright-report/* site/e2e

      - name: Publish GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
