name: 'Unit tests'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: Unit Tests Report
      url: ${{ steps.unit-tests-report.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install project dependencies
        run: yarn

      - name: Run unit tests
        run: yarn run test

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./reports/coverage/lcov-report

      - name: Upload GitHub Pages artifacts
        id: unit-tests-report
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: ./reports/coverage/lcov-report

  deploy-github-pages:
    permissions:
      pages: write
      id-token: write

    environment:
      name: Unit Tests Report
      url: ${{ steps.unit-tests-report.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: unit-tests

    steps:
      - name: Deploy to GitHub Pages
        id: unit-tests-report
        uses: actions/deploy-pages@v4
