name: 'Mutation tests'

on:
  workflow_dispatch:

jobs:
  mutation-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env

      - name: Run mutation tests
        run: yarn run test:mutation

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          path: ./reports/mutation

      - name: Create Report files
        if: ${{ always() }}
        run: |
          mkdir -p site/mutation
          cp -r ./reports/mutation/* site/mutation

      - name: Publish GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
