name: 'Mutation tests'

on:
  workflow_dispatch:

jobs:
  mutation-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install project dependencies
        run: yarn

      - name: Run mutation tests
        run: yarn run test:mutation

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: mutation-tests-report
          path: /reports/mutation/
          retention-days: 30
