name: 'E2E tests'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-env

      - name: Install Playwright browsers
        run: yarn playwright install

      - name: Run E2E tests
        run: yarn run e2e

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: E2E tests report - Zip file
          path: ./playwright-report

      - name: Publish GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report
          destination_dir: e2e
          publish_branch: gh-pages
